### ISSUE TITLE
Add Pagination for Dashboard Opportunities 

### ISSUE THREAD

**Issue by lpender2** [danmaisano/DojoGroupProject#50]
Add in pagination for the dashboard table when table consists of 10(?) or more opportunities.

**Comment by Harvey-Ryan** [comment]
If you make it pretty, it can be re-used anywhere. It's written as a standalone component.

**Comment by Harvey-Ryan** [comment]
I'll look into cleaning it up a bit more this weekend. It would be nice to handle all logic inside of Pagination.jsx and only have to pass state.

**Comment by Harvey-Ryan** [comment]
I made it prettier. Still need to look into simplifying the logic a bit into a self-contained Component.

**Comment by Harvey-Ryan** [comment]
It exists. Will work on cleaning it up later if we have time.
